site_name: HomeLab Docs
site_description: Documentation for my HomeLab projects
site_author: John Scalla
theme:
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/book
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Dark mode
      primary: blue grey
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@johnscalla
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/johnscalla
    - icon: fontawesome/brands/github
      link: https://github.com/johnscalla
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/johnpeterscalla
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/johnpeterscalla
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/johnscalla.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/johnscalla

copyright: "Copyright &copy; 2025 John Scalla"